#!/bin/bash
##############################################################
# name    : ArchiveToTape
# author  : Wim de Leeuw
# date    : 12-05-2017
# version : 0.1
# descript: Script to archive directory to tape 
##############################################################

PROG=`basename $0`
CFG_FILE="/usr/local/lib/SilsRdmTape.cfg"

REQUEST_ID=$1
TAPE_BARCODE=$2
LOCATION=$3
EXTERNAL_ID=$4
FORCE=$5


function error_exit {
    echo "$PROG failed: $1"
    exit 64
}

if [ -r $CFG_FILE ] ; then 
  . $CFG_FILE
else 
   error_exit "can not find find configuration file: $CFG_FILE"
fi


CONTENT_DIR="${META_DIR}/archive_content"
FORM_DIR="${META_DIR}/forms/processed"


if [ ! -f ${MT} ] ; then
  error_exit "tape operation program $MT not found"  
fi 

if [ ! -d ${META_DIR} ] ; then 
  error_exit "$META_DIR not found"  
fi

cd ${UPLOAD_DIR}

ARCHIVE_PATH="${UPLOAD_DIR}/${INTERNAL_ID}"

if [ $# -lt 4 ] ; then
  error_exit "at least 4 arguments needed : ArchiveID TapeBarcode TapeLocationNumber ExternalID [FORCE]"  
fi


QUERY="SELECT ArchiveID from Request WHERE ID='$REQUEST_ID'"
INTERNAL_ID=`echo $QUERY | $SQL_QUERY`


if [ "$INTERNAL_ID" == "" ] ; then 
  error_exit "Could not find RequestID : $REQUEST_ID"
fi 

Q1='SELECT `Group` FROM Request WHERE ID = "'$REQUEST_ID'"'
REQUEST_GROUP=`echo $Q1 | $SQL_QUERY`


Q2='SELECT `Group` FROM Tape WHERE Barcode = "'$TAPE_BARCODE'"'
TAPE_GROUP=`echo $Q2 | $SQL_QUERY`


if [ "$REQUEST_GROUP" != "$TAPE_GROUP" ]  ; then 
  error_exit "Group of tape $TAPE_BARCODE ($TAPE_GROUP) not equal to requesting group $REQUEST_GROUP"
fi 

APPLICATION_FORM=$FORM_DIR/${INTERNAL_ID}.pdf
if [ ! -r $APPLICATION_FORM ] ; then 
  error_exit "Processed application form ($APPLICATION_FORM) not found"
fi 

if [ ! -d "$ARCHIVE_PATH" ] ; then 
  error_exit "archive directory $ARCHIVE_PATH not found"
fi 

if [ ! -w "$ARCHIVE_PATH" ] ; then 
  error_exit "archive directory $ARCHIVE_PATH not writable, can not write metadata form"
fi 


#Check if barcode is valid
if [[ "$TAPE_BARCODE" != [0-9][0-9][0-9][0-9][0-9][0-9] ]] ; then
    error_exit "barcode has to be 6 digits"
fi

echo "Archiving $INTERNAL_ID"

cp $APPLICATION_FORM $ARCHIVE_PATH

if [ ! -f $ARCHIVE_PATH/${INTERNAL_ID}.pdf ] ; then 
    error_exit "Failed to copy metadata form into archive"
fi 

TAPE_STATUS=`${MT} status`

# Check if there is a tape in the drive
if echo $TAPE_STATUS | grep "DR_OPEN" > /dev/null; then
    error_exit "No tape in reader";
fi

# Check if tape write protected
if echo $TAPE_STATUS | grep "WR_PROT" > /dev/null; then
    error_exit "tape in reader has write protect tab switched on";
fi


${MT} asf 0 
ID_ON_TAPE=`cat $TAPE | jq -r ".TapeBarcode"`

if [ "$ID_ON_TAPE" != "$TAPE_BARCODE" ] ; then 
   error_exit "tape barcode mismatch tape has no or non matching label"
fi 

if [ "$LOCATION" -lt 1 ] ; then 
   error_exit "invalid tape location : $LOCATION"
fi 

if  ${MT} asf $LOCATION  ; then 
   if [ "$FORCE" != "FORCE" ] ; then 
       if ${MT} asf $((LOCATION+1))  2> /dev/null ; then 
          error_exit "not last record" 
       fi 
    else 
       echo "$PROG warning: tape overwritten"
    fi 
else 
   error_exit "requested tape location beyond current end"  
fi


MD5FILE=`mktemp /tmp/archMD5_XXXXXX`

find  $INTERNAL_ID  -type f -exec cat {} \; | md5sum > $MD5FILE

#use compression

${MT} compression 1

# tar the archive to tape 

${MT} asf ${LOCATION}
$TAR -c ${INTERNAL_ID} 
${MT} asf ${LOCATION}

# Check md5sum and fail if md5sum does not match which previously calculated value

$TAR -xO | md5sum  --quiet -c $MD5FILE 
if [ $? -eq 1 ] ; then 
    rm $MD5FILE
    error_exit "md5sum mismatch"
fi 

MD5SUM=`awk '{print $1}' $MD5FILE`
rm $MD5FILE

ls -alR ${INTERNAL_ID} > ${CONTENT_DIR}/${INTERNAL_ID}.toc
SQL_CMD='INSERT INTO Archive (Name,Barcode,TapeLocation,ExternalID,ArchiveDate,MD5sum,RequestID) VALUES ("'$INTERNAL_ID'","'$TAPE_BARCODE'",'$LOCATION',"'$EXTERNAL_ID'",CURDATE(),"'$MD5SUM'",'$REQUEST_ID');'
echo $SQL_CMD | ${SQL_QUERY}

if [ $? -ne 0 ] ; then 
    error_exit "Project archived, database entry failed"
fi

cp $APPLICATION_FORM /var/www/html/forms

if [ $? -ne 0 ] ; then 
    error_exit "Project archived, failed to copy application form"
fi

echo "Done" 
