#!/bin/bash
##############################################################
# name    : ListTape
# author  : Wim de Leeuw
# date    : 15-05-2017
# version : 0.1
# descript: Script to restore directory from tape 
##############################################################

PROG=`basename $0`
CFG_FILE="/usr/local/lib/SilsRdmTape.cfg"

function error_exit {
    echo "$PROG failed: $1"
    exit 64
}

function tape_overview {
    echo "Overview of known tapes (barcode:label-date:group:number:class:full)"
    echo 'SELECT * from Tape' | $SQL_QUERY
    echo "-----------------------------------"
    echo "Give barcode as parameter to get contents of specific tape"
} 

if [ -r $CFG_FILE ] ; then
  . $CFG_FILE
else
   error_exit "can not find find configuration file: $CFG_FILE"
fi

if [ $# -lt 1 ] ; then
  TAPE_STATUS=`$MT status`
  if echo $TAPE_STATUS | grep "DR_OPEN" > /dev/null; then
    tape_overview
    error_exit "no tape in reader";
  fi
  $MT asf 0
  TAPE_BARCODE=`cat $TAPE 2> /dev/null | jq -r ".TapeBarcode"`
  if [ "$TAPE_BARCODE" == "" ]  ; then
    tape_overview
    error_exit "tape in reader has no label";
  fi 
  echo "Information on tape $TAPE_BARCODE (now in reader):" 
else 
  TAPE_BARCODE=$1
  echo "Information on tape $TAPE_BARCODE:"
fi

SQL_CMD='SELECT * from Tape where Barcode = "'$TAPE_BARCODE'"'
echo "$SQL_CMD" | ${SQL_QUERY_HEADER}

if [ ! "$?" -eq 0 ]  ; then 
    error_exit "$1 is unknown or unlabeled (tape_barcode must be 6 digits)."
fi

echo "-----------------------------------"
echo "Data on tape"
SQL_CMD='SELECT * from Archive where Barcode = "'$TAPE_BARCODE'"'
echo "$SQL_CMD" | ${SQL_QUERY_HEADER}

if [ ! "$?" -eq 0 ]  ; then 
    error_exit "$1 empty tape."
fi
exit 0 
