#!/bin/bash

##############################################################
# name    : ListTape
# author  : Wim de Leeuw
# date    : 15-05-2017
# version : 0.1
# descript: Script to restore directory from tape 
##############################################################

PROG=`basename $0`

function error_exit {
    echo "$PROG failed: $1"
    exit 64
}

LOG_FILE="/archive/meta/archive_table"
TAPE_FILE="/archive/meta/tapes"

if [ ! -f $TAPE_FILE ] ; then
   error_exit "could not locate file with tape information"
fi

if [ ! -f $LOG_FILE ] ; then
   error_exit "could not locate file with archive information"
fi

if [ $# -lt 1 ] ; then
  echo "Overview of known tapes (barcode:label-date:group:number:class)"
  cat $TAPE_FILE
  echo "-----------------------------------"
  echo "Give barcode as parameter to get contents of specific tape"
  exit 0  
fi

TAPE_BARCODE=$1
echo TapeInfo: 
grep "^$TAPE_BARCODE	" $TAPE_FILE 

if [ ! "$?" -eq 0 ]  ; then 
    error_exit "$1 is unknown or unlabeled (tape_barcode must be 6 digits)."
fi

echo "-----------------------------------"
echo "Data on tape (barcode:slot:name:UID:archive-date:md5sum)"
grep "^$TAPE_BARCODE	" $LOG_FILE  

if [ ! "$?" -eq 0 ]  ; then 
    error_exit "$1 empty tape."
fi
exit 0 
