#!/bin/bash
##############################################################
# name    : RestoreFromTape
# author  : Wim de Leeuw
# date    : 12-05-2017
# version : 0.1
# descript: Script to restore directory from tape 
##############################################################

PROG=`basename $0`
CFG_FILE="/usr/local/lib/SilsRdmTape.cfg"

function error_exit {
    echo "$PROG failed: $1"
    exit 64
}

if [ -r $CFG_FILE ] ; then
  . $CFG_FILE
else
   error_exit "can not find find configuration file: $CFG_FILE"
fi

if [ $# -lt 1 ] ; then
  error_exit "Arguments needed : ArchiveName or Barcode and TapeLocationNumber"  
fi

if [ $# -lt 2 ] ; then
  ARCHIVE_NAME=$1
  SQL_CMD='SELECT Barcode from Archive where Name = "'$ARCHIVE_NAME'" '
  TAPE_BARCODE=(`echo $SQL_CMD | ${SQL_QUERY}`)
  if [ "${TAPE_BARCODE[0]}" == "" ] ; then 
      error_exit "An archive named $ARCHIVE_NAME is not known in database."
  fi 
else 
  TAPE_BARCODE=$1
  LOCATION=$2
  SQL_CMD='SELECT Name from Archive where Barcode = "'$TAPE_BARCODE'" and TapeLocation = '$LOCATION
  ARCHIVE_NAME=`echo $SQL_CMD | ${SQL_QUERY}`
fi 


if [ "$ARCHIVE_NAME" == "" ] ; then 
   if [ "$3" == "FORCE" ] ; then 
      ARCHIVE_NAME="Unamed_restore_`date +%d-%m-%Y`"
      ARCHIVE_MD5="Unknown (not in database)"
   else
      error_exit "This archive is not known in database. Use FORCE as third argument to restore Archive."
   fi
else
   SQL_CMD='SELECT MD5sum from Request where ArchiveID = "'$ARCHIVE_NAME'"' 
   ARCHIVE_MD5=`echo $SQL_CMD | ${SQL_QUERY}`
fi

echo "Restoring $ARCHIVE_NAME" 

if [ -d ${RESTORE_DIR}/$ARCHIVE_NAME ] ; then
   error_exit "${RESTORE_DIR}/$ARCHIVE_NAME exists."
fi

cd ${RESTORE_DIR}

TAPE_STATUS=`$MT status`

# Check if there is a tape in the drive
if echo $TAPE_STATUS | grep "DR_OPEN" > /dev/null; then
    error_exit "no tape in reader";
fi

$MT asf 0 

ID_ON_TAPE=`cat $TAPE 2> /dev/null | jq -r ".TapeBarcode"` 

TAPE_IN_READER=UNKNOWN
for tb in "${TAPE_BARCODE[@]}"
do
   if [ "$tb" == "$ID_ON_TAPE" ] ; then 
     TAPE_IN_READER=TRUE
   fi 
done

if [ "$TAPE_IN_READER" != "TRUE" ] ;  then
    error_exit "Tape not in reader. Archive $ARCHIVE_NAME is on tape(s): ${TAPE_BARCODE[*]}";
fi

if [ "$LOCATION" == "" ] ; then 
  SQL_CMD='SELECT TapeLocation from Archive where Name = "'$ARCHIVE_NAME'" and Barcode = "'$ID_ON_TAPE'"'
  LOCATION=`echo $SQL_CMD | ${SQL_QUERY}`
fi

if [ "$LOCATION" -lt 1 ] ; then 
   error_exit "invalid tape location : $LOCATION"
fi 

$MT asf $((LOCATION+1))
if [ $? -eq 1 ] ; then 
    error_exit "slot $LOCATION not found"
fi 

$MT asf ${LOCATION}

$TAR -x 
if [ $? -ne 0 ] ; then
    error_exit "tar from tape failed."
fi

MD5CHECK=`find $ARCHIVE_NAME  -type f -exec cat {} \; | md5sum | awk '{print $1}'`
if [ "${MD5CHECK}" !=  "${ARCHIVE_MD5}" ] ; then 
    error_exit "md5sum does not match value calculated before archiving ${MD5CHECK} != ${ARCHIVE_MD5}"
fi 

echo "$ARCHIVE_NAME sucessfully restored"

exit 0
